<?php
/**
 * Productattach template for separate item
 *
 */

/**
 * @var $this Krish\Productattach\Block\View
 * @see Krish\Productattach\Block\View
 */
?>
<?php 
//echo "test";
//echo $this->getCustomerId();

?>
<?php $productId = $this->getCurrentId(); ?>

<?php $attachments = $this->getAttachment($productId); ?>

<?php foreach ($attachments as $attachment): ?>
	<?php if($attachment->getActive()): ?>
	    <div>
	        <div class="product-attachment">
	        <?php if($attachment->getFile()): ?>
	        	<a href="<?php echo $this->getAttachmentUrl($attachment->getFile()) ?>" target="_blank">
	        		<?php echo $this->getFileIcon($attachment->getFile()) ?>
	        		<?php echo $attachment->getName() ?>
	        		<?php echo '( '.$this->getFileSize($attachment->getFile()).' )' ?>
	        	</a>
	        <?php else: ?>
	        	<a href="<?php echo $attachment->getUrl() ?>" target="_blank" >
	        		<?php echo $this->getFileIcon($attachment->getUrl()) ?>
	        		<?php echo $attachment->getName() ?>
	        	</a>
	        <?php endif; ?>
	        </div>
	    </div>
	<?php endif; ?>
<?php endforeach; ?>