<?php
/**
 * @var $this Prince\Productattach\Block\Attachment
 * @see Prince\Productattach\Block\Attachment
 */
?>
<?php $productId = $this->getCurrentId(); ?>
<?php $attachments = $this->getAttachment($productId); ?>
<?php $isSize = $this->getConfig('productattach/general/attachmentsize'); ?>

<?php foreach ($attachments as $attachment): ?>
	<?php if($attachment->getActive()): ?>
	    <div>
	        <div class="product-attachment">
	        <?php if($attachment->getFile()): ?>
	        	<a href="<?php echo $this->getAttachmentUrl($attachment->getFile()) ?>" target="_blank">
	        		<?php echo $this->getFileIcon($attachment->getFile()) ?>
	        		<?php echo $attachment->getName() ?>
	        		<?php if($isSize): ?>
	        			<?php echo '('.$this->getFileSize($attachment->getFile()).')' ?>
	        		<?php endif; ?>
	        	</a>
	        <?php else: ?>
	        	<a href="<?php echo $attachment->getUrl() ?>" target="_blank" >
	        		<?php echo $this->getFileIcon($attachment->getUrl()) ?>
	        		<?php echo $attachment->getName() ?>
	        	</a>
	        <?php endif; ?>
	        </div>
	    </div>
	<?php endif; ?>
<?php endforeach; ?>